name: CI

on: [push, pull_request]

env:
  KBRANCH: v5.8
  SLEEP_A_BIT: sleep 0.2
  VERBOSE: 1

jobs:
  musl-x86_64-nostacktrace:
    runs-on: ubuntu-latest
    env:
      CC: musl-gcc
      STACKTRACE: no
      TARGET: x86_64
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: install dependencies
      run: ci/install-dependencies.sh
    - name: build check
      run: ci/run-build-and-tests.sh
